on: [push, pull_request]


jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.te_st }}
      output2: ${{ steps.step2.outputs.te_st }}
    steps:
    - id: step1
      run: |
        echo -n "::set-output name=te_st::"
        pwd
    - id: step2
      run: echo "::set-output name=te_st::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo o1: ${{needs.job1.outputs.output1}} o2: ${{needs.job1.outputs.output2}}


